name: Node Setup
description: Set up Node environment and install requirements

runs:
  using: "composite"
  steps:
  - uses: actions/checkout@v5
  - uses: actions/setup-node@v6
    with:
      node-version: 24
  - run: npm ci