name: TESTS

on:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    name: test
    steps:
      - uses: ./.github/actions/setup

      - name: Run unit-tests
        run: npm run test
